### ISSUE TITLE
Add issuer identifier and previous entity hash to the published event

### ISSUE THREAD

**Issue by alejandro-nieto-git** [alastria/DOME-blockchain_smart_contracts#1]
It is now required that we store a hashed identifier of the entity publishing the event in the blockchain instead of the userEthereumAddress. We must store an additional argument called previousEntityHash which is also a hash.

**Comment by Alexander-Herranz** [comment]
**To Define**

- "userEthereum" changed to hash: Do we know the hash data type?
- Add new property "previousEntityHash": Is it a single value, or array?
- Technical data architecture for on-chain events' state storage: How to query state (active = true) events (ordered by date)? (Struct + Mapping design)

**Comment by Alexander-Herranz** [comment]
**Defined**

- "userEthereum" changed to hash value (from address value): Do we know the hash data type? **SHA-256 (...so bytes32 type in Solidity)**
- Add new property "previousEntityHash": Is it a single value, or array? **Single Value**
- Technical data architecture for on-chain events' state storage: How to query state (active = true) events (ordered by date)? (Struct + Mapping design) **TO-DO**
- New SHA-256 variable (entityIDHash) that need to be filtered (by date).

**Comment by alejandro-nieto-git** [comment]
We must have a "previousEntityHash" field of bytes32 in the event too. We only have the entityIDHash until now.
